name: grammer
description: A library to process noun (plural to singular and singular to plural), verb (gerund, present & past) and adjective (comparative, superlative) transformations.

version: 1.0.3
homepage: https://github.com/justkawal/grammer

environment:
  sdk: '>=2.15.1 <3.3.6'

dependencies:
  stemmer: ^2.2.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
