name: grammer
description: A library to process noun (plural to singular and singular to plural), verb (gerund, present & past) and adjective (comparative, superlative) transformations.

version: 1.0.2
homepage: https://github.com/justkawal/grammer

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  stemmer: ^2.2.0

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.16.0
