name: grammer
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://www.github.com/justkawal

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  stemmer: ^2.2.0

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.16.0
